version: 2.1
jobs:
  build:
    docker:
      - image: currusci/flutter
    steps
      - checkout
      - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-debug.apk